# Generated by Django 5.2.4 on 2025-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
    ]
