# Generated by Django 5.2.4 on 2025-11-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
